### ISSUE TITLE
Fix Misskey instance information fetch

### ISSUE THREAD

**Issue by perillamint** [Interstellar-Relay-Community/aode-relay#1]
Currently, AodeRelay tries to fetch from `/api/v1/instance`, which does not exist in Misskey.

This should be resolved in a proper way, to improve Misskey interoperability.

Log entry

```
relay_1  | 2022-12-14T17:32:52.360016Z  WARN relay::requests: Response from https://[REDACTED]/api/v1/instance, Not Found
```

**Comment by perillamint** [comment]
in `src/jobs/instance.rs:48`, it should be modified to attempt some endpoints for various Fedi implementation.

`api/v1/instance` only covers Mastodon (maybe Pleroma?) and it should handle Misskey case, `api/meta`

Note that Misskey requires HTTP POST method to access the API, may require to apply some "hack" on `src/requests.rs:272`

**Comment by asonix** [comment]
You're right that `/api/v1/instance` is specific to mastodon (and also implemented by pleroma). I think adding new requests for misskey makes sense, but ultimately since these are all implementation-specific, we can't ensure it works for every software

**Comment by perillamint** [comment]
Another problem is, Misskey does not restrict administrator parameter to be configured as Fediverse handle.

This may require some alternative implementation for Misskey to fetch server information

```
{
  "maintainerName": "Caipira",
  "maintainerEmail": "[REDACTED],
  "version": "12.120.0-alpha.8+cs",
  "name": "Stella",
```

**Comment by perillamint** [comment]
Currently fixing this in dev/msky-support branch. 

To reuse most of mastodon-supoort code, it would be nice to implement some sort of translator between Misskey meta and mastodon instance information data structure.

**Comment by perillamint** [comment]
Initial implementation pushed in dev/msky-support. Note that the commit needs some refactoring to merged into the production.

**Comment by perillamint** [comment]
Further upstreaming task will be handled in #5
