### ISSUE TITLE
arm64 docker images

### ISSUE THREAD

**Issue by sussycatgirl** [Interstellar-Relay-Community/aode-relay#30]
Hi,

I'm running the relay on a cheap ARM based VPS, but I have to build the docker image myself which is fairly resource intensive and takes a while. If you'd be willing to spend the extra compute power, I believe adding arm64 builds would be a single line change in [the workflow](https://github.com/Interstellar-Relay-Community/aode-relay/blob/interstellar-next/.github/workflows/build-image.yml#L47) as described here: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by perillamint** [comment]
Sorry for the late reply.

I'm Currently considering the following options to produce AArch64 build

1. Use a real machine to build AArch64 binaries, buy one Mac mini, install Asahi, and run GitHub Action runner on it
2. Somehow do a cross build to improve compilation performance. (need to solve OpenSSL dependency)
3. Run it in a VM, using traditional docker multiplatform build.

I'll comment in here after doing some experiments internally.

**Comment by perillamint** [comment]
@sussycatgirl I... actually tried enabling it in the past, but it only gave me one virtual ARM processor, which results in extremely slow build time. (the self-hosted runner is running on the 32-core Threadripper machine, but the docker cross build process only utilize single core thus 31-core was wasted)

If you know how to solve this issue, please let me know. (I'm fairly new to new docker build process)

**Comment by sussycatgirl** [comment]
Oh okay, makes sense. I honestly don't have much knowledge of the topic either, but I appreciate the effort :3

**Comment by perillamint** [comment]
@sussycatgirl Fixed in #31, will be deployed within hour, but noted AArch64 build will not be got intensive testing compared to AMD64 one, due to primary deployment target is currently AMD64 VM

**Comment by perillamint** [comment]
CI workflow does not work well due to tempdir persistency, currently resolving on it

**Comment by perillamint** [comment]
@sussycatgirl Finally I got some time and implemented AArch64 build properly.
