### ISSUE TITLE
페디버스 서버 증대에 따른 서버 목록 문제 보조 방안 제언

### ISSUE THREAD

**Issue by fofwisdom** [Interstellar-Relay-Community/aode-relay#36]
### 문제
여러 위키 기여자가 페디버스 서버 목록을 나열하고자 노력하고 있지만 이용자 수가 많은 주요 서버의 등재에 그치고 있습니다.

### 해결 방안
위키 기여자는 릴레이 서버에 연결된 서버 목록 외부 링크만 남기도록 하고, 릴레이 서버에서 연결된 서버 나열 시주요 특징 및 기능을 함께 나열하여 표지 역할을 합니다.

#### 나열할 서버 특징 제안
1. 주제
2. 소프트웨어

#### 나열할 서버 기능 제안
1. 전문 검색
2. 기계 번역 

### 목적 및 효과
소수 서버의 소외를 최소화합니다.

페디버스의 규모를 잠재 이용자에게 부각합니다.

### 구현 방안
1. 릴레이 서버가 정보수집을 위한 추가 통신
2. 페디버스 관리자가 릴레이 서버에 등록하는 관리자 계정의 프로필 메타에 릴레이 서버가 정한 텍스트 규칙 대로 내용 작성하고 릴레이 서버가 이를 수집

**Comment by perillamint** [comment]
Upstream 과 지나치게 멀어지게 되어 유지 보수 코스트가 지나치게 증가할 것으로 추산되는 바, 이를 해결하기 위해서는 릴레이 서버의 수정보다는 별도의 프로젝트를 진행하는 것이 올바를 것으로 보입니다.

더불어, 관리자 계정보다는, 현재 사용중인 `/api/v1/instance` 의 short_description 혹은 description 필드 또는 `/api/meta` 의 description 필드를 사용하는 것이 더 나을 것입니다.

**Comment by perillamint** [comment]
필요하다면, 현재 릴레이에 있는 인스턴스들의 목록을 제공하는 퍼블릭 API 엔드포인트 제공 까지는 가능하겠지만, 그 이상의 무언가는 힘들 것으로 예측됩니다.
